### PR TITLE
New communication layer between R and threads

### PR DESCRIPTION
**Pull request by nx10**
This PR is a rewrite of the IPC and execution layer used to communicate with R from off the main thread.

The excellent `later` package was used previously but it has some constraints (due to different use cases) that are not appropriate for httpgd.

This PR is a complete replacement with less overhead and modern C++ features and lets us call into R even when the R session is not idle. It basically treats the session as the only worker of a thread pool and allows to individually await execution of C++ futures that run on the main thread.

Fixes: https://github.com/nx10/httpgd/issues/83
Will enable: https://github.com/nx10/httpgd/issues/94
This also will make writing and debugging async communication code for httpgd a lot easier.

I tested this on Windows 10 and a fedora VM, but it would be great if it was tested in more environments before I merge.

### CODE REVIEW

**Comment by eitsupi** [comment]
I ran the sample code in #83 on the Docker image `r-base` (Debian-based), and it worked well.

**Comment by renkun-ken** [comment]
Tried this PR and it works quite nicely!

**Comment by eitsupi** [comment]
I also tried it with `r-base` on arm64 (Raspberry Pi 4), and it seems to work just as well.

**Comment by nx10** [comment]
Thank you both for testing!

**Pull request merged**
